###
GET http://localhost:9970/tasks
###
GET http://localhost:9970/tasksByProjectId/?projectId=2
###
GET http://localhost:9970/users
###
GET http://localhost:9970/teams
###
GET http://localhost:9970/projects
###
GET http://localhost:9970/projectsByTeamId/?teamId=1
###
GET http://localhost:9970/phases


###
POST http://localhost:9970/teams
Content-Type: application/json

{
  "title": "team added from http client"
}
###
POST http://localhost:9970/projects
Content-Type: application/json

{
  "title": "project added from http client",
  "team_id": 2
}
###
POST http://localhost:9970/tasks
Content-Type: application/json

{
  "description": "task 5 added from http client",
  "project_id": 2
}

###
PUT http://localhost:9970/tasks
Content-Type: application/json

{
  "description": "blue task updated from http client",
  "project_id": 3,
  "phase_id": 2,
  "id": 2
}



